<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_settings</name>
   <tag></tag>
   <elementGuidId>fb623bb6-3b17-4f73-8588-96963712b952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mat-tooltip-trigger.cdk-focused.cdk-mouse-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/div[3]/app-header-user-menu/div/div/div[4]/div[4]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5aadbceb-db75-430c-b5a3-d0bf14a83b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltip</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>73c6a7fb-38d5-4bc1-9dfe-0f8822826219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltipclass</name>
      <type>Main</type>
      <value>tooltip-font-size tooltip-position14</value>
      <webElementGuid>11e9a901-7271-46a5-ac69-cb609b17b0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/setting</value>
      <webElementGuid>f6cac3c2-cfa4-43ed-b7b2-1d842d58ff10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-tooltip-trigger cdk-focused cdk-mouse-focused</value>
      <webElementGuid>befa0889-24eb-468a-9acd-73d8faa7205a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-cpd-1-10</value>
      <webElementGuid>cc309a98-ee82-43e6-b5d6-45c75b59a5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdk-describedby-host</name>
      <type>Main</type>
      <value>cpd-1</value>
      <webElementGuid>6a288e27-c8e0-4012-af1d-14e1079417bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>settings</value>
      <webElementGuid>ffaa9b54-b10f-4ed3-9935-daf5e30abe87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-main ng-tns-c629-4&quot;]/div[@class=&quot;headerinner ng-tns-c629-4&quot;]/div[@class=&quot;header-user-menu ng-tns-c629-4&quot;]/app-header-user-menu[@class=&quot;ng-tns-c629-4&quot;]/div[@class=&quot;headrhtmainright&quot;]/div[@class=&quot;userbox d-flex align-items-center&quot;]/div[@class=&quot;iconWrapper&quot;]/div[@class=&quot;mainsettingbox ng-star-inserted&quot;]/div[@class=&quot;mainSetting heading&quot;]/a[@class=&quot;mat-tooltip-trigger cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>ea2ecc45-2c8e-481f-aa05-8437af18d952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div[3]/app-header-user-menu/div/div/div[4]/div[4]/div/a</value>
      <webElementGuid>d35450fc-9560-4e77-bc1b-37e8f990a462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='notifications'])[1]/following::a[1]</value>
      <webElementGuid>6f0e1e6e-3758-4fa7-81df-71c8878807ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Search'])[2]/following::a[2]</value>
      <webElementGuid>b44ada6d-409b-4556-acdf-b679f4838781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello, testowner live'])[1]/preceding::a[1]</value>
      <webElementGuid>442d3c69-b1c1-4d66-a112-b553e40afb3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice Analytics'])[1]/preceding::a[1]</value>
      <webElementGuid>9ea8ea03-71ba-4a15-b52d-3fd094bdb529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/setting')]</value>
      <webElementGuid>39fe9311-6b52-43fe-8b78-da8a0940d8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>3824a3ab-69a9-4093-99f2-fc4f18951cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/setting' and (text() = 'settings' or . = 'settings')]</value>
      <webElementGuid>3f6969f8-aec7-4564-8f20-3bb0e2e72e71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
