<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Assign Role_mat-select-arrow ng-tns-c291-26</name>
   <tag></tag>
   <elementGuidId>7ca2dbff-8186-4841-abd5-17c386529349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow.ng-tns-c291-26</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='mat-select-0']/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>95230d6b-41cd-499b-a6a5-cd6eb2198f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow ng-tns-c291-26</value>
      <webElementGuid>e309c013-f5cb-4e9f-9b11-54ee1162f3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-0&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c291-26&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c291-26&quot;]/div[@class=&quot;mat-select-arrow ng-tns-c291-26&quot;]</value>
      <webElementGuid>f9bc7bf0-af86-47bb-9bdc-60da1f426ab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-0']/div/div[2]/div</value>
      <webElementGuid>3e5c2196-f49c-4a60-a77c-27b6221fa183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div[2]/div</value>
      <webElementGuid>a15a06a6-8499-4752-9cb6-0bb6637ba6b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
