<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_mat-input-6</name>
   <tag></tag>
   <elementGuidId>dcd27dc6-8232-4f61-bb32-72c36ce3dc62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de6999c9-ad37-42c7-9fbf-79dd2bdedf61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>last_name</value>
      <webElementGuid>8af75f83-9bca-4174-995b-58de4f32f5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>730e807a-ba99-41dd-bee0-c9d1e2386aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c192-22 ng-untouched cdk-text-field-autofill-monitored ng-dirty ng-invalid</value>
      <webElementGuid>8f158f50-7ee4-45cb-ba5e-d42c051fb2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-6</value>
      <webElementGuid>f5bd00bc-4b0f-495b-8e07-1525702ea717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>c148b069-d35c-4a8a-927e-36b9a6c891f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>83db9e15-d9f9-499b-89d9-a93e960af7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>39db43d3-f569-48b5-9c28-557b3f7e7626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-6&quot;)</value>
      <webElementGuid>94135df1-b2b9-4b78-b108-71516fcb43ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-6']</value>
      <webElementGuid>ad42c3ac-a1d5-4a2b-bb1f-81bd1fc839b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-1-0']/form/div[2]/div/div[2]/mat-form-field/div/div/div/input</value>
      <webElementGuid>de9bb66a-b420-4f7a-8bd4-0d75320bb6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div[2]/mat-form-field/div/div/div/input</value>
      <webElementGuid>b0316bf4-e7d7-4c64-8a85-f7151c122dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-input-6']</value>
      <webElementGuid>484fa026-ca10-414a-a6db-c6ca43e92c0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
