<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_settings</name>
   <tag></tag>
   <elementGuidId>3eadad40-c1f0-41ce-b7fc-fa7a44128cce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mat-tooltip-trigger.cdk-focused.cdk-mouse-focused > mat-icon.mat-icon.notranslate.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/div[3]/app-header-user-menu/div/div/div[4]/div[4]/div/a/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>190f5a4d-4871-427a-8569-62b6745694f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c28bf973-cb27-4e62-bce9-fa33ea78f503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>d48f5a5f-e0b7-4c3f-81fc-19b3d47b9612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7cabf4db-82c0-4761-b510-a170df27a535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>99e249b1-c1a3-497b-af08-f643f606d274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>settings</value>
      <webElementGuid>44315dde-e823-4244-9eff-5e070868ad40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-main ng-tns-c629-4&quot;]/div[@class=&quot;headerinner ng-tns-c629-4&quot;]/div[@class=&quot;header-user-menu ng-tns-c629-4&quot;]/app-header-user-menu[@class=&quot;ng-tns-c629-4&quot;]/div[@class=&quot;headrhtmainright&quot;]/div[@class=&quot;userbox d-flex align-items-center&quot;]/div[@class=&quot;iconWrapper&quot;]/div[@class=&quot;mainsettingbox ng-star-inserted&quot;]/div[@class=&quot;mainSetting heading&quot;]/a[@class=&quot;mat-tooltip-trigger cdk-focused cdk-mouse-focused&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>604cf714-b497-408c-abfa-73bc991246b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div[3]/app-header-user-menu/div/div/div[4]/div[4]/div/a/mat-icon</value>
      <webElementGuid>5ef3419b-df1a-413a-8821-458afe641c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='notifications'])[1]/following::mat-icon[1]</value>
      <webElementGuid>52e0043d-7a74-4ab5-97a2-36937330214d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Search'])[2]/following::mat-icon[3]</value>
      <webElementGuid>546de756-dd85-43fc-895a-23dd75f3e679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello, testowner live'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>fcf80def-8bec-4072-bc13-7ef830da4047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice Analytics'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>638848e5-5553-4c92-aa81-a5c8d0ea3c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='settings']/parent::*</value>
      <webElementGuid>34155d77-c6d7-42f6-9dc7-f9ebdbfbb727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/mat-icon</value>
      <webElementGuid>e89f4602-0906-4b03-90eb-765d8bb4f982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'settings' or . = 'settings')]</value>
      <webElementGuid>856488da-9f13-4e00-a23b-cddc7154d271</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
