<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Applications keyboard_arrow_right</name>
   <tag></tag>
   <elementGuidId>8fe45160-ca0a-4feb-8d80-33c6d446d555</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appsidebar']/div/div/div/nav/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c1eb04ae-62bc-41f7-86be-718c9bb651a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/setting/admin/applications</value>
      <webElementGuid>5e47ea4f-240e-4db8-b8f9-a14946439ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4662c959-ef86-4f22-80dd-c0f634b42096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9795b54a-e1a7-4d03-a966-02c635fc1262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseExample</value>
      <webElementGuid>78f5a19a-8726-44d5-b50f-04d4ca37c562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link ng-tns-c635-16 ng-star-inserted</value>
      <webElementGuid>8947c6ee-e722-4019-81a6-c5362693cf98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Applications keyboard_arrow_right</value>
      <webElementGuid>2436f437-32aa-4fd6-ad25-0c20cf7af11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appsidebar&quot;)/div[@class=&quot;innersidebar ng-tns-c635-16&quot;]/div[@class=&quot;sidebarblock ng-tns-c635-16&quot;]/div[@class=&quot;sidebarnavbox ng-tns-c635-16&quot;]/nav[@class=&quot;servloc-navbar ng-tns-c635-16&quot;]/div[@class=&quot;nav-item dropdown adminSideBar ng-tns-c635-16&quot;]/a[@class=&quot;nav-link ng-tns-c635-16 ng-star-inserted&quot;]</value>
      <webElementGuid>48714f85-d224-42a8-9fce-2a52d09fb78f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appsidebar']/div/div/div/nav/div/a[2]</value>
      <webElementGuid>2c12271f-e4de-4b44-bb10-9ad3392b89be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Panel'])[2]/following::a[2]</value>
      <webElementGuid>78329f81-c5c4-4a5f-ab49-0db62487adb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Applications']/parent::*</value>
      <webElementGuid>aa2d4e5c-152b-4d35-8c77-f891d90813d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/setting/admin/applications')]</value>
      <webElementGuid>64eb4347-b461-4748-800f-bb0581ba2444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>56dc44ba-7ca5-4cbc-aa4e-26dd5ac1f1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/setting/admin/applications' and (text() = ' Applications keyboard_arrow_right' or . = ' Applications keyboard_arrow_right')]</value>
      <webElementGuid>6826d3e1-c516-4a99-9715-f5ea9cec9647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
