<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ct box</name>
   <tag></tag>
   <elementGuidId>b4527630-7a36-49b1-9b57-3facfb6ff037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontainer']/div/div/div/div/app-setting-admin/app-application-list/div/div[11]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>402827ae-1e9d-4d0c-bfe1-fc999deccc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>appshedulebox border p-24 br-4</value>
      <webElementGuid>b3e5906f-d96b-408c-83fc-7ee19a07fcfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Call TrackingAllows you to track all of your incoming phone calls, see where they are coming from, and how your front desk is performing.account_circleActive Users23location_onActive Locations10 </value>
      <webElementGuid>8e8b506e-270d-4c9d-af3e-d477e0a654dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontainer&quot;)/div[@class=&quot;innermaincontainer&quot;]/div[@class=&quot;maincontainerblock clearfix&quot;]/div[@class=&quot;innermaincontent&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-setting-admin[@class=&quot;ng-star-inserted&quot;]/app-application-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mainappsection appboxes ng-star-inserted&quot;]/div[@class=&quot;appitem ng-star-inserted&quot;]/div[@class=&quot;appshedulebox border p-24 br-4&quot;]</value>
      <webElementGuid>ec698415-4eef-43cd-a0bd-afe16e0fbe19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/app-setting-admin/app-application-list/div/div[11]/div</value>
      <webElementGuid>2e3a511a-46cf-4056-aee7-9dc712a2b568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active Locations'])[10]/following::div[5]</value>
      <webElementGuid>daffa471-687e-40ba-bd35-6b240be5c04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active Users'])[10]/following::div[9]</value>
      <webElementGuid>d02bc8f1-f259-4e71-935a-b0fb1416f7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div</value>
      <webElementGuid>e7d57f8c-edb1-43b0-9329-389e4efdedc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Call TrackingAllows you to track all of your incoming phone calls, see where they are coming from, and how your front desk is performing.account_circleActive Users23location_onActive Locations10 ' or . = 'Call TrackingAllows you to track all of your incoming phone calls, see where they are coming from, and how your front desk is performing.account_circleActive Users23location_onActive Locations10 ')]</value>
      <webElementGuid>90b61572-c046-4039-b5de-44d50c79f3df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
