<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Practice Analytics</name>
   <tag></tag>
   <elementGuidId>caa243e5-371b-4c96-99c3-d437dddda98a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.appshedulebox.border.p-24.br-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontainer']/div/div/div/div/app-setting-admin/app-application-list/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b88ca32a-ba71-4c60-92d4-0548f6319c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>appshedulebox border p-24 br-4</value>
      <webElementGuid>0a02f6b9-3b28-4356-86a3-ffecb3801115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Practice AnalyticsAmplifies your practice with metrics, KPIs, and targeted patient lists that can help you increase production, retention, and overall practice success.account_circleActive Users23location_onActive Locations9 </value>
      <webElementGuid>1fd59152-cf0b-4417-86fb-3204dcf8b3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontainer&quot;)/div[@class=&quot;innermaincontainer&quot;]/div[@class=&quot;maincontainerblock clearfix&quot;]/div[@class=&quot;innermaincontent&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-setting-admin[@class=&quot;ng-star-inserted&quot;]/app-application-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mainappsection appboxes ng-star-inserted&quot;]/div[@class=&quot;appitem ng-star-inserted&quot;]/div[@class=&quot;appshedulebox border p-24 br-4&quot;]</value>
      <webElementGuid>3332b96e-5d5f-4eaf-b9cc-248f4ec33af8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/app-setting-admin/app-application-list/div/div/div</value>
      <webElementGuid>b1d1e140-c821-41e3-99d6-50142e50fcd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps'])[1]/following::div[3]</value>
      <webElementGuid>8b4fc397-8659-4fd8-b9c5-1f076b31998a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-application-list/div/div/div</value>
      <webElementGuid>8fb1aa38-0539-4b82-b077-13d0d0d66990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Practice AnalyticsAmplifies your practice with metrics, KPIs, and targeted patient lists that can help you increase production, retention, and overall practice success.account_circleActive Users23location_onActive Locations9 ' or . = 'Practice AnalyticsAmplifies your practice with metrics, KPIs, and targeted patient lists that can help you increase production, retention, and overall practice success.account_circleActive Users23location_onActive Locations9 ')]</value>
      <webElementGuid>2b8f3004-1165-4208-b0c7-9c328a3212e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
