<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>engage box</name>
   <tag></tag>
   <elementGuidId>a60af530-b879-4920-a6c1-d60d37505b1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontainer']/div/div/div/div/app-setting-admin/app-application-list/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a623481-fb7b-4abf-9f94-7b9722fcd5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>appshedulebox border p-24 br-4</value>
      <webElementGuid>b34760d6-7228-4b0f-a562-b7d59776461b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EngageConnect with patients via text, call, or email, and perform practice-related functions efficiently in a centralized patient info display.account_circleActive Users23location_onActive Locations10 </value>
      <webElementGuid>869ebafb-5a6c-49f2-ae78-0acc70ffd898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontainer&quot;)/div[@class=&quot;innermaincontainer&quot;]/div[@class=&quot;maincontainerblock clearfix&quot;]/div[@class=&quot;innermaincontent&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-setting-admin[@class=&quot;ng-star-inserted&quot;]/app-application-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mainappsection appboxes ng-star-inserted&quot;]/div[@class=&quot;appitem ng-star-inserted&quot;]/div[@class=&quot;appshedulebox border p-24 br-4&quot;]</value>
      <webElementGuid>7db5689b-38e5-4d8d-a91d-e1ca8830fc27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/app-setting-admin/app-application-list/div/div[2]/div</value>
      <webElementGuid>d61b6ef8-a09b-4adc-b43d-2f21d6905531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active Locations'])[1]/following::div[5]</value>
      <webElementGuid>f8a98475-14e2-4e05-bf95-74cb46d20db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active Users'])[1]/following::div[9]</value>
      <webElementGuid>401ab26e-7a42-47ea-8757-f1decaecc870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-application-list/div/div[2]/div</value>
      <webElementGuid>2d9e3eea-ef38-4ded-8c8f-452da1fe9dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'EngageConnect with patients via text, call, or email, and perform practice-related functions efficiently in a centralized patient info display.account_circleActive Users23location_onActive Locations10 ' or . = 'EngageConnect with patients via text, call, or email, and perform practice-related functions efficiently in a centralized patient info display.account_circleActive Users23location_onActive Locations10 ')]</value>
      <webElementGuid>b078686a-bdc6-42e1-be7f-b26107b1522c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
