<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PA</name>
   <tag></tag>
   <elementGuidId>f1240818-a5ef-4aa1-8eaa-718cd04d5f3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.appshedulebox.border.p-24.br-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>Pa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8caffdd7-e268-4f98-8135-25ffc5e2a27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>appshedulebox border p-24 br-4</value>
      <webElementGuid>0d3ea7d4-687f-47b0-a480-4a9afc47f4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Practice AnalyticsAmplifies your practice with metrics, KPIs, and targeted patient lists that can help you increase production, retention, and overall practice success.account_circleActive Users23location_onActive Locations9 </value>
      <webElementGuid>a8a3cee3-6cdb-4ae0-9792-24b48dfe6ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontainer&quot;)/div[@class=&quot;innermaincontainer&quot;]/div[@class=&quot;maincontainerblock clearfix&quot;]/div[@class=&quot;innermaincontent&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-setting-admin[@class=&quot;ng-star-inserted&quot;]/app-application-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mainappsection appboxes ng-star-inserted&quot;]/div[@class=&quot;appitem ng-star-inserted&quot;]/div[@class=&quot;appshedulebox border p-24 br-4&quot;]</value>
      <webElementGuid>e923cbbf-b5fc-4bad-87bf-94614b396be4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/app-setting-admin/app-application-list/div/div/div</value>
      <webElementGuid>757ad206-7c80-48c8-99b5-e9ec5dea2eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps'])[1]/following::div[3]</value>
      <webElementGuid>583d9692-0f2c-4580-914d-9e22e043a2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-application-list/div/div/div</value>
      <webElementGuid>d8a06874-aad4-40e1-bfa5-e4aa6109018b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Practice AnalyticsAmplifies your practice with metrics, KPIs, and targeted patient lists that can help you increase production, retention, and overall practice success.account_circleActive Users23location_onActive Locations9 ' or . = 'Practice AnalyticsAmplifies your practice with metrics, KPIs, and targeted patient lists that can help you increase production, retention, and overall practice success.account_circleActive Users23location_onActive Locations9 ')]</value>
      <webElementGuid>be704345-bb75-40a3-a771-14e8f8c832af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
