<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Users keyboard_arrow_right</name>
   <tag></tag>
   <elementGuidId>1823920e-feae-4b76-b45f-5d91c8ea2675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appsidebar']/div/div/div/nav/div/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f9d7b4ab-9ca8-4849-a451-b0ff544f0bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/setting/admin/user/list</value>
      <webElementGuid>726309f6-f5d7-4336-aec2-b0392d22df86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>409ae4eb-6291-47f5-ba13-7db2a6007de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c4f2e951-11e4-4f94-9191-ac2efab5105c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseExample</value>
      <webElementGuid>e0242058-65bc-46ea-a96e-c050a7c3baf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link ng-tns-c635-16 ng-star-inserted</value>
      <webElementGuid>d9e8f91d-183e-4494-b551-a136e7a010ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Users keyboard_arrow_right</value>
      <webElementGuid>3bdd5929-3fea-4970-b97e-b299714f442c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appsidebar&quot;)/div[@class=&quot;innersidebar ng-tns-c635-16&quot;]/div[@class=&quot;sidebarblock ng-tns-c635-16&quot;]/div[@class=&quot;sidebarnavbox ng-tns-c635-16&quot;]/nav[@class=&quot;servloc-navbar ng-tns-c635-16&quot;]/div[@class=&quot;nav-item dropdown adminSideBar ng-tns-c635-16&quot;]/a[@class=&quot;nav-link ng-tns-c635-16 ng-star-inserted&quot;]</value>
      <webElementGuid>ac5c6c42-2a1d-4a30-87f7-0f90ab1341b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appsidebar']/div/div/div/nav/div/a[3]</value>
      <webElementGuid>31a394f6-d2e8-4c43-aeb4-77edcf144335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization'])[1]/preceding::a[2]</value>
      <webElementGuid>ca8b62de-a207-48ef-97ee-65166b1ae2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Users']/parent::*</value>
      <webElementGuid>4e63c861-4859-478e-8922-1d2b40a4ad14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/setting/admin/user/list')]</value>
      <webElementGuid>d243b201-188f-4427-aa09-5f23f23eb316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>5539223a-e459-486a-b6d7-757a34f00e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/setting/admin/user/list' and (text() = ' Users keyboard_arrow_right' or . = ' Users keyboard_arrow_right')]</value>
      <webElementGuid>55d294b6-1e0a-48f6-97a4-9c5c74bb85d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
