<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Assign Role_mat-select-arrow ng-tns-c291-32</name>
   <tag></tag>
   <elementGuidId>64db999e-4a95-4239-a360-e4205648c8e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow.ng-tns-c291-32</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='mat-select-2']/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7f5053b7-a475-4167-8553-64af19a87776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow ng-tns-c291-32</value>
      <webElementGuid>810aa153-6ee1-418d-92dc-84cdacf30f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-2&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c291-32&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c291-32&quot;]/div[@class=&quot;mat-select-arrow ng-tns-c291-32&quot;]</value>
      <webElementGuid>7acf1535-3e13-460b-a7db-b965bba5b33a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-2']/div/div[2]/div</value>
      <webElementGuid>35368608-bc29-4dc6-a716-674f5073b852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div[2]/div</value>
      <webElementGuid>d05aa69b-3f67-43b9-84dc-28477fd09dcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
