<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Billing keyboard_arrow_right</name>
   <tag></tag>
   <elementGuidId>ab60bc15-72f6-4277-a587-9e0c82f77d64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appsidebar']/div/div/div/nav/div/a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>13b6820f-698f-4090-b162-b47829af905f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/setting/admin/billing</value>
      <webElementGuid>36832143-bf36-4ef7-b961-f9c8122821e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>756d26da-6111-4905-baff-4fa6dc00391f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>766145b0-8b51-4981-8093-fd6237b641bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseExample</value>
      <webElementGuid>fbe23ed6-56e3-43a5-ba60-49cbefcda872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link ng-tns-c635-16 ng-star-inserted</value>
      <webElementGuid>1db24d2a-0a18-469a-8a1c-05485d65e585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Billing keyboard_arrow_right</value>
      <webElementGuid>0bedfed0-89a7-4798-a49f-29604357d6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appsidebar&quot;)/div[@class=&quot;innersidebar ng-tns-c635-16&quot;]/div[@class=&quot;sidebarblock ng-tns-c635-16&quot;]/div[@class=&quot;sidebarnavbox ng-tns-c635-16&quot;]/nav[@class=&quot;servloc-navbar ng-tns-c635-16&quot;]/div[@class=&quot;nav-item dropdown adminSideBar ng-tns-c635-16&quot;]/a[@class=&quot;nav-link ng-tns-c635-16 ng-star-inserted&quot;]</value>
      <webElementGuid>b50f937c-d574-425b-af17-813a936cfd6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appsidebar']/div/div/div/nav/div/a[4]</value>
      <webElementGuid>029d6511-01b3-41f1-8193-f59e2404b8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization'])[1]/preceding::a[1]</value>
      <webElementGuid>1e3383e3-ace1-464b-a262-96aa14e64500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test org1'])[1]/preceding::a[1]</value>
      <webElementGuid>037a0714-4684-445c-9264-c49814f1ece9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Billing']/parent::*</value>
      <webElementGuid>b5a77b28-5eaa-4118-a3c9-89e98118c5db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/setting/admin/billing')]</value>
      <webElementGuid>af20d78c-1826-4e02-84a0-c87b8be2cc0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>39f6b0ee-0ab4-4b32-a3e9-77eda31135d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/setting/admin/billing' and (text() = ' Billing keyboard_arrow_right' or . = ' Billing keyboard_arrow_right')]</value>
      <webElementGuid>89d03a40-b7ae-4d30-ba76-8bafc7b791a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
