<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Generates a single invoice for the entire organization with any number of locations. Also, only one payment method is allowed for the entire organization</name>
   <tag></tag>
   <elementGuidId>a1d3fe7c-5413-4856-b5d8-75dcb1d1f76e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.mb-20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontainer']/div/div/div/div/app-setting-admin/app-billing-overview/div[2]/div/div/div/form/div/mat-radio-group/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c83cdbeb-77a2-4577-9121-c06b6d522030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-20</value>
      <webElementGuid>ce71cba9-199d-4d45-bde7-fdb00cf7d77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generates a single invoice for the entire organization with any number of locations. Also, only one payment method is allowed for the entire organization.</value>
      <webElementGuid>b2cade57-7965-473f-8b38-912f43c6a0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontainer&quot;)/div[@class=&quot;innermaincontainer&quot;]/div[@class=&quot;maincontainerblock clearfix&quot;]/div[@class=&quot;innermaincontent&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-setting-admin[@class=&quot;ng-star-inserted&quot;]/app-billing-overview[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;fuse-card auto-width p-24 br-4 customheightbox&quot;]/div[@class=&quot;billingoverviewcontent&quot;]/div[@class=&quot;billingbox&quot;]/div[@class=&quot;billinglist&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;ordernewcompany&quot;]/mat-radio-group[@class=&quot;mat-radio-group vertical-radio-group ng-untouched ng-pristine ng-valid&quot;]/p[@class=&quot;mb-20&quot;]</value>
      <webElementGuid>7cc8bc3b-c4fd-49c8-a3af-43fd63116c42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/app-setting-admin/app-billing-overview/div[2]/div/div/div/form/div/mat-radio-group/p</value>
      <webElementGuid>9f7ec24a-59cd-4bbc-b353-ec3347ec87b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Preference'])[1]/following::p[1]</value>
      <webElementGuid>646fc691-5ca4-4bec-a7af-a02e83035b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test org1'])[1]/preceding::p[2]</value>
      <webElementGuid>b2705b66-cc17-47ae-b19e-0ac9f73dd232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generates a single invoice for the entire organization with any number of locations. Also, only one payment method is allowed for the entire organization.']/parent::*</value>
      <webElementGuid>3d236550-50e4-419f-8209-5727689e7328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>a0ce7c43-3843-48b5-84f5-2a5921baa2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Generates a single invoice for the entire organization with any number of locations. Also, only one payment method is allowed for the entire organization.' or . = 'Generates a single invoice for the entire organization with any number of locations. Also, only one payment method is allowed for the entire organization.')]</value>
      <webElementGuid>39f95fa3-0153-4848-bbd5-a805efcf99f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
