<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Location Level Billing</name>
   <tag></tag>
   <elementGuidId>8e27afd0-5833-4bb4-928b-ef239b8d1c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-radio-3 > label.mat-radio-label > span.mat-radio-label-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-radio-button[@id='mat-radio-3']/label/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d9be1f04-8db4-4b2d-8392-8988856e859d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-radio-label-content</value>
      <webElementGuid>22aa2bec-a142-4095-a1a2-d0663bbf52d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Location Level Billing</value>
      <webElementGuid>0b3cf8f1-1d5b-44ee-a0de-17d93de42d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-radio-3&quot;)/label[@class=&quot;mat-radio-label&quot;]/span[@class=&quot;mat-radio-label-content&quot;]</value>
      <webElementGuid>7e7a9c06-dc38-44e7-bc93-18bde1a1fbd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='mat-radio-3']/label/span[2]</value>
      <webElementGuid>e0335a2b-72db-40dd-8cd7-4f7468b51eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Preference'])[1]/following::span[13]</value>
      <webElementGuid>6536ec1e-6d3f-49a6-a046-747581ad9e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test org1'])[1]/preceding::span[2]</value>
      <webElementGuid>75cb3847-fb0c-42f2-84de-3f9aa9f0fe94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[1]/preceding::span[2]</value>
      <webElementGuid>b20bce29-1475-4106-91ab-dc637e18561d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Location Level Billing']/parent::*</value>
      <webElementGuid>d501e2fd-b3d9-4f5c-95e4-d4942644b018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-radio-button[2]/label/span[2]</value>
      <webElementGuid>609b5ffd-92f9-4a05-a55f-8a665807d301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Location Level Billing' or . = ' Location Level Billing')]</value>
      <webElementGuid>3b8fbf6a-2526-4ab5-affe-fdafcb397fc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
