<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>d23d9c2e-deb6-4bc5-b9a3-164f4fcdc258</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.ng-tns-c633-17.mat-flat-button.mat-button-base.mat-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='editorganization clearfix']/div/form/div/div[5]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>302308af-f455-4728-9d1e-9792bfca63ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>1cbe6213-5c10-4168-924a-70709a6c70b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator ng-tns-c633-17 mat-flat-button mat-button-base mat-primary</value>
      <webElementGuid>5e3eaeff-dc20-46a2-9d4c-d51fc8139917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>9b95da56-9feb-4a9c-bc29-54ccea53febe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editorganization clearfix&quot;)/div[@class=&quot;fuse-card auto-width p-24 br-4 customheightbox ng-tns-c633-17&quot;]/form[@class=&quot;ng-tns-c633-17 ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;editorgrow ng-tns-c633-17&quot;]/div[@class=&quot;editorgbox ng-tns-c633-17&quot;]/div[@class=&quot;editorganizationcol2 ng-tns-c633-17&quot;]/div[@class=&quot;editorgbtnbox ng-tns-c633-17&quot;]/button[@class=&quot;mat-focus-indicator ng-tns-c633-17 mat-flat-button mat-button-base mat-primary&quot;]</value>
      <webElementGuid>97d80c88-3827-48be-b973-bde56ef3abed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='editorganization clearfix']/div/form/div/div[5]/div/div/button</value>
      <webElementGuid>772b7600-7575-4908-bde6-ea6272584fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Changes'])[1]/preceding::button[1]</value>
      <webElementGuid>e542bcdc-f801-4476-876e-aa917ea41d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/button</value>
      <webElementGuid>80dc6cc1-dd58-4b3f-ae3f-83c200815260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>64d017a1-d92c-4b09-a0a6-afa0ea04af96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
