<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Users keyboard_arrow_right</name>
   <tag></tag>
   <elementGuidId>5786643d-8393-4452-b311-13490618878d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appsidebar']/div/div/div/nav/div/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a88ec2d0-46bc-44f0-8d7b-dc67fdee8f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/setting/admin/user/list</value>
      <webElementGuid>ac52de4f-6ae9-4b9f-8a8f-18f05e81cdee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>468c7c6c-764b-4c91-b798-42cda794fd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>81be39d7-a4ea-49e1-82d1-7a88be59f2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseExample</value>
      <webElementGuid>42bdb058-8f10-4db8-a707-c7eb30e4f0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link ng-tns-c635-16 ng-star-inserted</value>
      <webElementGuid>4d4110f2-d008-43c4-8136-1fd6ac883c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Users keyboard_arrow_right</value>
      <webElementGuid>96ab2613-cd4c-435f-b30c-499fcc0baaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appsidebar&quot;)/div[@class=&quot;innersidebar ng-tns-c635-16&quot;]/div[@class=&quot;sidebarblock ng-tns-c635-16&quot;]/div[@class=&quot;sidebarnavbox ng-tns-c635-16&quot;]/nav[@class=&quot;servloc-navbar ng-tns-c635-16&quot;]/div[@class=&quot;nav-item dropdown adminSideBar ng-tns-c635-16&quot;]/a[@class=&quot;nav-link ng-tns-c635-16 ng-star-inserted&quot;]</value>
      <webElementGuid>f572d9b1-0509-4b2d-ae6d-83a996858084</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appsidebar']/div/div/div/nav/div/a[3]</value>
      <webElementGuid>fb02d10a-fb66-4585-a04f-08df334d21f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization'])[1]/preceding::a[2]</value>
      <webElementGuid>7ae94695-2d5c-4c40-8e3d-f1e6864db8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Users']/parent::*</value>
      <webElementGuid>e46d1565-5558-4191-b1ef-6918bfe9df2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/setting/admin/user/list')]</value>
      <webElementGuid>bc999ef6-ad65-4a7b-8308-dd5fc1ef539f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>495aeddb-0d37-45d9-9dfc-72d8708c87da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/setting/admin/user/list' and (text() = ' Users keyboard_arrow_right' or . = ' Users keyboard_arrow_right')]</value>
      <webElementGuid>9b55dded-4af1-4b8b-810a-be1657c6b998</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
