<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_settings</name>
   <tag></tag>
   <elementGuidId>d635adb5-9542-41e3-9d10-9ccc8b207c05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mat-tooltip-trigger.cdk-focused.cdk-mouse-focused > mat-icon.mat-icon.notranslate.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/div[3]/app-header-user-menu/div/div/div[4]/div[4]/div/a/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>3c779bcd-98ce-4fb4-9ca8-86f6b5a60222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>893f8aba-6842-412a-802e-84b2f38fadc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>010e8d60-17ac-4150-bd4c-fc783ad47c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>81ac2edb-5531-4070-8a6c-a313553bfb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>5ccec18d-2f7f-45c1-be63-2afa3634ff05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>settings</value>
      <webElementGuid>2bad32fb-e20f-4e64-9642-863ae1da6c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-main ng-tns-c629-4&quot;]/div[@class=&quot;headerinner ng-tns-c629-4&quot;]/div[@class=&quot;header-user-menu ng-tns-c629-4&quot;]/app-header-user-menu[@class=&quot;ng-tns-c629-4&quot;]/div[@class=&quot;headrhtmainright&quot;]/div[@class=&quot;userbox d-flex align-items-center&quot;]/div[@class=&quot;iconWrapper&quot;]/div[@class=&quot;mainsettingbox ng-star-inserted&quot;]/div[@class=&quot;mainSetting heading&quot;]/a[@class=&quot;mat-tooltip-trigger cdk-focused cdk-mouse-focused&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>6dec91ca-d698-4320-975c-94661d6ac953</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div[3]/app-header-user-menu/div/div/div[4]/div[4]/div/a/mat-icon</value>
      <webElementGuid>55b76052-61ae-47be-ac72-348557ace92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='notifications'])[1]/following::mat-icon[1]</value>
      <webElementGuid>38d2fbae-64d5-4594-9f48-b8bdb1a443bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Search'])[2]/following::mat-icon[3]</value>
      <webElementGuid>32624707-28ce-444a-ba17-2fe45564d7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello, testowner live'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>b6494790-5c2b-4b06-ac32-c84914f67902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice Analytics'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>0871582f-1bfe-41d1-9f52-ccd00ee8c106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='settings']/parent::*</value>
      <webElementGuid>102f8b39-4903-482a-996e-79ad18d2abd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/mat-icon</value>
      <webElementGuid>2bd593c5-017c-4ba0-b5f7-3877a3670872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'settings' or . = 'settings')]</value>
      <webElementGuid>89bf4650-9d45-43a5-abdc-e8691118bcac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
