<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Billing keyboard_arrow_right</name>
   <tag></tag>
   <elementGuidId>ee99b389-021f-4f16-88e4-a4a1b728cb6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appsidebar']/div/div/div/nav/div/a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>992f58fc-0732-467d-9870-48ffa28bcbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/setting/admin/billing</value>
      <webElementGuid>bf4a2412-2d55-42c8-9974-e8c941ce0391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2b359b23-ea39-4e4b-bf4b-77c727117132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d54ef636-ef33-404a-9655-7edb1a7a1caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseExample</value>
      <webElementGuid>6f66c5a3-ad7d-41e5-a2a1-20fea9a609b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link ng-tns-c635-16 ng-star-inserted</value>
      <webElementGuid>a191b4e7-27e8-47c9-a48c-a085c671b31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Billing keyboard_arrow_right</value>
      <webElementGuid>a921a546-5652-4fa7-8965-1b5b589e2173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appsidebar&quot;)/div[@class=&quot;innersidebar ng-tns-c635-16&quot;]/div[@class=&quot;sidebarblock ng-tns-c635-16&quot;]/div[@class=&quot;sidebarnavbox ng-tns-c635-16&quot;]/nav[@class=&quot;servloc-navbar ng-tns-c635-16&quot;]/div[@class=&quot;nav-item dropdown adminSideBar ng-tns-c635-16&quot;]/a[@class=&quot;nav-link ng-tns-c635-16 ng-star-inserted&quot;]</value>
      <webElementGuid>ea95946b-4637-49fb-9bef-47ce8a85c78c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appsidebar']/div/div/div/nav/div/a[4]</value>
      <webElementGuid>6c9f8a60-8f9b-444d-8aea-9e3a4d46c16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization'])[1]/preceding::a[1]</value>
      <webElementGuid>4473432c-d962-486a-8335-71c70e5e11c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test org1'])[1]/preceding::a[1]</value>
      <webElementGuid>f23615dc-037f-4171-b0dd-3f1a9cb19e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Billing']/parent::*</value>
      <webElementGuid>5cdf8aaf-e504-4868-83e3-8f43bb55c4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/setting/admin/billing')]</value>
      <webElementGuid>6163ddec-6c74-46bf-bd1b-83caa27941c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>bfaedcd8-6660-4345-bbfa-46dad62bad07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/setting/admin/billing' and (text() = ' Billing keyboard_arrow_right' or . = ' Billing keyboard_arrow_right')]</value>
      <webElementGuid>8ea85559-609d-4016-a26b-d660d9e607dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
