<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_V2</name>
   <tag></tag>
   <elementGuidId>a3bb5be4-f191-47a8-9126-3374b5a9d956</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='dropdownmenu_billing']/div/div[13]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9e47c340-e159-4044-8e84-53ba3a21a7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>261b6ac5-4494-42d3-99c0-91b974159dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1b29f836-bc01-47a0-b40e-1f463a28f5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1d49db56-e3cc-4783-8ee9-368b0527c6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseExample</value>
      <webElementGuid>dd24a047-b477-4bcc-a0be-890d29c3fc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 ng-tns-c635-16</value>
      <webElementGuid>82dd7d32-615e-4878-9ca6-b73f675d63c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> V2 </value>
      <webElementGuid>cf977058-9b73-430f-b23c-1ca1af1c86a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownmenu_billing&quot;)/div[@class=&quot;sideinnermenu ng-tns-c635-16&quot;]/div[@class=&quot;dropdown ng-tns-c635-16 ng-star-inserted&quot;]/div[@class=&quot;sidemenu ng-tns-c635-16&quot;]/button[@class=&quot;mb-2 ng-tns-c635-16&quot;]</value>
      <webElementGuid>2328b4ad-ec7f-4c19-a266-2bc43dc69549</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='dropdownmenu_billing']/div/div[13]/div/button</value>
      <webElementGuid>ecde5f92-3198-4ce0-8583-b880323ff7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TextLoc'])[1]/following::button[1]</value>
      <webElementGuid>db68334b-087a-457f-bf4a-39014b7ddeca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testlocation4'])[1]/following::button[2]</value>
      <webElementGuid>d66058dd-39cc-4341-89cf-e4dfcd25e7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='V2-no landline'])[1]/preceding::button[1]</value>
      <webElementGuid>050c778e-dbf0-4964-87e7-7ac08c12d6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='V2']/parent::*</value>
      <webElementGuid>2f021da9-ce63-4052-a28d-19c0f37ff2e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/button</value>
      <webElementGuid>4269f957-ad71-40d7-9d62-6be68b9b53bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@href = 'javascript:void(0)' and (text() = ' V2 ' or . = ' V2 ')]</value>
      <webElementGuid>094a91d3-5288-4a65-9904-94a0d99d3c79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
