<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_settings</name>
   <tag></tag>
   <elementGuidId>1b83bb02-00e5-4e86-80b6-b2961ce06d6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mat-tooltip-trigger.cdk-focused.cdk-mouse-focused > mat-icon.mat-icon.notranslate.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/div[3]/app-header-user-menu/div/div/div[4]/div[4]/div/a/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>7b5880cd-18df-439b-a59a-236bb430f704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>deb034af-eaec-413c-86c6-2b3f9c840a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>d30786c6-f389-4af9-a255-edc3d3db5fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>88858538-411b-4b12-ad10-0914783bf62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>889a2ee4-24a4-4668-a41b-b0f433ad6aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>settings</value>
      <webElementGuid>0f212419-e170-48c1-9850-c0abe483162a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-main ng-tns-c629-4&quot;]/div[@class=&quot;headerinner ng-tns-c629-4&quot;]/div[@class=&quot;header-user-menu ng-tns-c629-4&quot;]/app-header-user-menu[@class=&quot;ng-tns-c629-4&quot;]/div[@class=&quot;headrhtmainright&quot;]/div[@class=&quot;userbox d-flex align-items-center&quot;]/div[@class=&quot;iconWrapper&quot;]/div[@class=&quot;mainsettingbox ng-star-inserted&quot;]/div[@class=&quot;mainSetting heading&quot;]/a[@class=&quot;mat-tooltip-trigger cdk-focused cdk-mouse-focused&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>7659ac1c-e2c5-4d61-b449-8195059e1b0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div[3]/app-header-user-menu/div/div/div[4]/div[4]/div/a/mat-icon</value>
      <webElementGuid>b97a5869-23bb-4ca0-926e-93399dba5d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='notifications'])[1]/following::mat-icon[1]</value>
      <webElementGuid>1359f51d-ae31-4592-a740-6b451eddea84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Search'])[2]/following::mat-icon[3]</value>
      <webElementGuid>ff098a05-31e9-42ec-b5d0-f2edec09bb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello, testowner live'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>16034d3e-cff5-472e-beec-662835f0e32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice Analytics'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>a45a0113-b71e-4601-9657-7245ddd0fd83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='settings']/parent::*</value>
      <webElementGuid>678e6442-3139-4083-8ba0-cb9e2ed88ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/mat-icon</value>
      <webElementGuid>7fb75622-7697-4ea5-8cc0-64e42f56f90b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'settings' or . = 'settings')]</value>
      <webElementGuid>616ed428-44b1-4496-ab24-71dc7d3d2a7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
