<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Numbers</name>
   <tag></tag>
   <elementGuidId>44a07b3a-248b-4686-9c37-bda87318508d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.splashmenucol.splashmenucol2 > div.splashmenuheadbox > h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontainer']/div/div/div/div/div/div[2]/div[2]/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>6cb35074-736c-43c5-b94b-1043828676c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Numbers</value>
      <webElementGuid>7692eb4d-3714-474b-92bb-6c3d945bed11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontainer&quot;)/div[@class=&quot;innermaincontainer&quot;]/div[@class=&quot;maincontainerblock clearfix&quot;]/div[@class=&quot;innermaincontent&quot;]/div[@class=&quot;splashsectionbox ng-star-inserted&quot;]/div[@class=&quot;splashscreenrow&quot;]/div[@class=&quot;splashmenubox clearfix&quot;]/div[@class=&quot;splashmenucol splashmenucol2&quot;]/div[@class=&quot;splashmenuheadbox&quot;]/h3[1]</value>
      <webElementGuid>180801ca-48c4-48d8-a3fb-9568da3a8674</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/div/div[2]/div[2]/div/h3</value>
      <webElementGuid>8d00ae1c-331c-4803-b191-b5e72cb3d600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing'])[1]/following::h3[1]</value>
      <webElementGuid>56b34035-74d2-4fe2-acdc-9e3683869512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::h3[1]</value>
      <webElementGuid>34229e9b-fdfb-4399-b1b5-cc23aa62b6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number List'])[1]/preceding::h3[1]</value>
      <webElementGuid>717bb311-1b5c-48db-a0ec-5bdfa66aa205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Call Flow'])[1]/preceding::h3[1]</value>
      <webElementGuid>1f4a2415-1b83-4b9f-9f8b-21ca0b6e7aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h3</value>
      <webElementGuid>8eeaa9d2-a11e-4ba8-8a85-a671bfd546d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Numbers' or . = 'Numbers')]</value>
      <webElementGuid>c881aa44-4918-4702-900a-92dac41573e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
