<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_settings</name>
   <tag></tag>
   <elementGuidId>3bb02d8d-8407-41da-a9be-35a593461e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mat-tooltip-trigger.cdk-focused.cdk-mouse-focused > mat-icon.mat-icon.notranslate.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/div[3]/app-header-user-menu/div/div/div[4]/div[4]/div/a/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>c05bb799-87c8-4fc6-bf09-1ce1aad3cc45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cd1a019c-a1af-49c2-9f0d-5d1386551eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>afcef343-8cb6-44c0-ab4b-85c020313f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>401852cb-1f67-4470-a96c-a7b755e53f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>e5a6634e-5133-42cd-bfdb-a894b73fad5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>settings</value>
      <webElementGuid>9e2b915b-706e-4714-a324-203c9952f4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-main ng-tns-c629-4&quot;]/div[@class=&quot;headerinner ng-tns-c629-4&quot;]/div[@class=&quot;header-user-menu ng-tns-c629-4&quot;]/app-header-user-menu[@class=&quot;ng-tns-c629-4&quot;]/div[@class=&quot;headrhtmainright&quot;]/div[@class=&quot;userbox d-flex align-items-center&quot;]/div[@class=&quot;iconWrapper&quot;]/div[@class=&quot;mainsettingbox ng-star-inserted&quot;]/div[@class=&quot;mainSetting heading&quot;]/a[@class=&quot;mat-tooltip-trigger cdk-focused cdk-mouse-focused&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>262e3cc8-b3f1-42b8-865f-ae318ae2b1aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div[3]/app-header-user-menu/div/div/div[4]/div[4]/div/a/mat-icon</value>
      <webElementGuid>3fb00416-7d72-4dc5-92d2-41d113b6a714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='notifications'])[1]/following::mat-icon[1]</value>
      <webElementGuid>fcdb5eb0-1006-4712-8e38-5d92eb01fa54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Search'])[2]/following::mat-icon[3]</value>
      <webElementGuid>2a8bf71d-da7d-4238-8ff6-7aac0801f91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello, testowner live'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>671fe705-5f29-4d05-8421-647f4f60b2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice Analytics'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>a2d15d7d-340a-4b22-ae3f-8c8fa06146ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='settings']/parent::*</value>
      <webElementGuid>fd76d4fe-cf6d-4d99-a609-65a1a6ff28ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/mat-icon</value>
      <webElementGuid>16ab28d8-f27c-49cc-83aa-0f2ddbc344f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'settings' or . = 'settings')]</value>
      <webElementGuid>7df80751-79f6-4e1d-ab2d-ec00fcde286b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
