<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_BH</name>
   <tag></tag>
   <elementGuidId>617290cf-8659-4467-a396-68165ad44383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.tbllocationicon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontainer']/div/div/div/div/app-setting-admin/app-user-detail/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a4a9a306-c2a3-4932-b8fb-3c3ae49e6887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tbllocationicon</value>
      <webElementGuid>287a3a50-54b4-4c89-91e2-00929ccb7614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BH</value>
      <webElementGuid>ebc69fd9-4d5a-4453-ac8e-85cdaaec1354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontainer&quot;)/div[@class=&quot;innermaincontainer&quot;]/div[@class=&quot;maincontainerblock clearfix&quot;]/div[@class=&quot;innermaincontent&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-setting-admin[@class=&quot;ng-star-inserted&quot;]/app-user-detail[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;fuse-card auto-width p-24 br-4 customheightbox ng-star-inserted&quot;]/div[@class=&quot;locdetailheadrow clearfix&quot;]/div[@class=&quot;tbllocationbox&quot;]/span[@class=&quot;tbllocationicon&quot;]</value>
      <webElementGuid>4bc8d4ca-1002-4122-bf9d-12e30c1dce13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/app-setting-admin/app-user-detail/div/div/div/span</value>
      <webElementGuid>0ff31334-c834-4d3d-a953-4dff7fb720b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Detail'])[1]/following::span[1]</value>
      <webElementGuid>f75f3f9a-6323-42d1-b383-4ff00d45fa81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bhavin@adit.com'])[1]/preceding::span[2]</value>
      <webElementGuid>6ccab444-3c3a-4aa6-a802-d6efa8876c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BH']/parent::*</value>
      <webElementGuid>a371f9b1-a4ba-4f60-8b15-44ba3cfbea75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-user-detail/div/div/div/span</value>
      <webElementGuid>745db066-5a13-4862-ad8b-869023aab777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'BH' or . = 'BH')]</value>
      <webElementGuid>ab69dba4-9858-4b5d-bca5-41332aaccfb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
