<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Applications</name>
   <tag></tag>
   <elementGuidId>e4fc553a-4d90-4d25-8e59-42a15380592d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.loctiongsubtitle.mb-0 > strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontainer']/div/div/div/div/app-setting-admin/app-user-detail/div/div[4]/div/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>684b2851-9462-4285-aa91-00fbf3da844d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Applications</value>
      <webElementGuid>e244bc26-129e-40ba-aae5-675b634a2f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontainer&quot;)/div[@class=&quot;innermaincontainer&quot;]/div[@class=&quot;maincontainerblock clearfix&quot;]/div[@class=&quot;innermaincontent&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-setting-admin[@class=&quot;ng-star-inserted&quot;]/app-user-detail[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;fuse-card auto-width p-24 br-4 customheightbox ng-star-inserted&quot;]/div[@class=&quot;locauseraccess pb-24&quot;]/div[@class=&quot;loctiongsubtitle mb-0&quot;]/strong[1]</value>
      <webElementGuid>898e664e-afb5-4272-a769-c8944942f6b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/app-setting-admin/app-user-detail/div/div[4]/div/strong</value>
      <webElementGuid>56dcfc80-0f03-46ac-a816-f3fcf2fd5aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='V2-no landline'])[1]/following::strong[1]</value>
      <webElementGuid>7439648e-09ba-45fa-adc0-1b8d9c66aac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VL'])[1]/following::strong[1]</value>
      <webElementGuid>4eb17bef-c0c0-4736-80af-ab73583919fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pozative'])[1]/preceding::strong[1]</value>
      <webElementGuid>ba1ddd69-3ada-47c7-a945-cdcf9e83344d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TeleMed'])[1]/preceding::strong[1]</value>
      <webElementGuid>dac9ef5c-7d62-4780-8d10-7be572067a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/strong</value>
      <webElementGuid>c72ed830-9958-4d7a-b207-95111a0f7b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Applications' or . = 'Applications')]</value>
      <webElementGuid>4fa2bf22-98dc-4034-9f0a-a474050e4370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
